[geyser-spigot]
src.manual = "latest"
fetch.url = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
url.name = "Geyser-Spigot.jar"
fetch.force = true

[floodgate-spigot]
src.manual = "latest"
fetch.url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
url.name = "Floodgate-Spigot.jar"
fetch.force = true

[floodgate-sqlite-database]
src.manual = "latest"
fetch.url = "https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/fix-weird-via-issue/lastSuccessfulBuild/artifact/database/sqlite/build/libs/floodgate-sqlite-database.jar"
url.name = "floodgate-sqlite-database.jar"
fetch.force = true

[viaversion]
src.github = "ViaVersion/ViaVersion"
fetch.url = "https://github.com/ViaVersion/ViaVersion/releases/download/$ver/ViaVersion-$ver.jar"
url.name = "ViaVersion.jar"

[authme]
src.github = "AuthMe/AuthMeReloaded"
fetch.url = "https://github.com/AuthMe/AuthMeReloaded/releases/download/$ver/AuthMe-$ver.jar"
url.name = "AuthMe.jar"

[skinsrestorer]
src.github = "SkinsRestorer/SkinsRestorer"
fetch.url = "https://github.com/SkinsRestorer/SkinsRestorer/releases/download/$ver/SkinsRestorer.jar"
url.name = "SkinsRestorer.jar"
